//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApiTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class BillingApiTestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BillingApiTestSettings defaultInstance = ((BillingApiTestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BillingApiTestSettings())));
        
        public static BillingApiTestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://host1.test-billing.services.trupanion.com")]
        public string BillingServiceBaseUrlTestEnvironment {
            get {
                return ((string)(this["BillingServiceBaseUrlTestEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Njg2NTkxMDcsImV4cCI6MTU2OTI2MzkwNywiaXNzIjoidGVzdC1hcHAwMS50cnVpZC50cnVwYW5pb24uY29tIiwiYXVkIjoidGVzdC5zZXJ2aWNlcy50cnVwYW5pb24uY29tIiwianRpIjoiNTNiNmZhNmNkZmNkNDc1NmI5Y2JlNmQ2NWM5N2U3N2QiLCJUcnVJZCI6eyJJZCI6IjA4MDkyYWFhMmNlNjQ2ZjA4ZGJiMzc3OGVkNDM0NGQ4IiwiVXNlciI6Inl1bmZlbmcubWEiLCJOYW1lIjoiWXVuZmVuZyBNYSIsIlNjb3BlIjowfX0=.DN4F10I85s5vKfFKnykDNwEW/1Lc6Est5vupyvzSnMY=")]
        public string BillingServiceAuthorizationTokenTestEnvironment {
            get {
                return ((string)(this["BillingServiceAuthorizationTokenTestEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("632810")]
        public int BillingServiceApiAccountId {
            get {
                return ((int)(this["BillingServiceApiAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c590d48-7aed-4651-ad48-08e10954b523")]
        public string BillingServiceApiAccountPartyId {
            get {
                return ((string)(this["BillingServiceApiAccountPartyId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("305155")]
        public string BillingServiceApiAccountPolicyHolderId {
            get {
                return ((string)(this["BillingServiceApiAccountPolicyHolderId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640261")]
        public int BillingServiceApiAccountTruDatOwnerId {
            get {
                return ((int)(this["BillingServiceApiAccountTruDatOwnerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("637943BC-D0C4-4A0B-B7D8-55BC78FFE65F")]
        public string BillingServiceApiAccountTruDatOwnerUniqueId {
            get {
                return ((string)(this["BillingServiceApiAccountTruDatOwnerUniqueId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24.33")]
        public decimal BillingServiceApiAccountNextInvoiceAmount {
            get {
                return ((decimal)(this["BillingServiceApiAccountNextInvoiceAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0b96e1d3cc1016e223b5af45afd")]
        public string BillingServiceApiAccountExternalId {
            get {
                return ((string)(this["BillingServiceApiAccountExternalId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miao Laoshi")]
        public string BillingServiceApiBankAccountNameOnAccount {
            get {
                return ((string)(this["BillingServiceApiBankAccountNameOnAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142048")]
        public int BillingServiceApiBankAccountId {
            get {
                return ((int)(this["BillingServiceApiBankAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test-app01.corp.vetinsurance.com")]
        public string BillingServiceManchineName {
            get {
                return ((string)(this["BillingServiceManchineName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trupanion.Billing.WebService")]
        public string BillingServiceName {
            get {
                return ((string)(this["BillingServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checking")]
        public string BillingServiceTypesChecking {
            get {
                return ((string)(this["BillingServiceTypesChecking"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0fa6e1d3d17016e223b61986db1")]
        public string BillingServiceApiAccountInvoiceId {
            get {
                return ((string)(this["BillingServiceApiAccountInvoiceId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4608")]
        public int BillingServiceApiAccountPaymentReschedulingRrequestsId {
            get {
                return ((int)(this["BillingServiceApiAccountPaymentReschedulingRrequestsId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70.92")]
        public decimal BillingServiceApiAccountInoiceAmount {
            get {
                return ((decimal)(this["BillingServiceApiAccountInoiceAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pet Insurance")]
        public string BillingServiceProductsName {
            get {
                return ((string)(this["BillingServiceProductsName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int BillingServiceProductsNumber {
            get {
                return ((int)(this["BillingServiceProductsNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0fa6e87ff56016e897b3d08707d")]
        public string BillingServiceApiAccountInoiceIdUnMatched {
            get {
                return ((string)(this["BillingServiceApiAccountInoiceIdUnMatched"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0f86e690391016e7f85caae067f")]
        public string BillingServiceApiAccountInvoicePaymentId {
            get {
                return ((string)(this["BillingServiceApiAccountInvoicePaymentId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35.0")]
        public decimal BillingServiceApiAccountInvoiceItemChargeAmount {
            get {
                return ((decimal)(this["BillingServiceApiAccountInvoiceItemChargeAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0f8557bc1f401557f2ceb5e1d31")]
        public string BillingServiceProductId {
            get {
                return ((string)(this["BillingServiceProductId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int BillingServiceApiAccounPaymentMethodsCount {
            get {
                return ((int)(this["BillingServiceApiAccounPaymentMethodsCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visa")]
        public string BillingServiceApiAccounPaymentMethodsCreditCardType {
            get {
                return ((string)(this["BillingServiceApiAccounPaymentMethodsCreditCardType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Checking")]
        public string BillingServiceApiAccounPaymentMethodsBankAccountType {
            get {
                return ((string)(this["BillingServiceApiAccounPaymentMethodsBankAccountType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0fa6ea67ac8016ea965669c4689")]
        public string BillingServiceApiPaymentCollectionsAccountId {
            get {
                return ((string)(this["BillingServiceApiPaymentCollectionsAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0fa6e87ff4c016e942844da2276")]
        public string BillingServiceApiAccountDefaultPaymentMethodId {
            get {
                return ((string)(this["BillingServiceApiAccountDefaultPaymentMethodId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int BillingServiceApiAccountBillingCycleDay {
            get {
                return ((int)(this["BillingServiceApiAccountBillingCycleDay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9037bc8a-b526-400e-a9b9-02b67c7db5f9")]
        public global::System.Guid BillingServiceApiAccountCharityIdUS {
            get {
                return ((global::System.Guid)(this["BillingServiceApiAccountCharityIdUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c6f9d451-d092-4df4-8b01-2ed552d7fcf2")]
        public global::System.Guid BillingServiceApiAccountNonReferencedCreditMethodTypeIdUS {
            get {
                return ((global::System.Guid)(this["BillingServiceApiAccountNonReferencedCreditMethodTypeIdUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0b96e1d3cc1016e223b5af45afd")]
        public string BillingAccountUpdateTestAccountId {
            get {
                return ((string)(this["BillingAccountUpdateTestAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int BillingAccountUpdateTestBillCycleDay {
            get {
                return ((int)(this["BillingAccountUpdateTestBillCycleDay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9037bc8a-b526-400e-a9b9-02b67c7db5f9")]
        public global::System.Guid BillingAccountUpdateTestCharityId {
            get {
                return ((global::System.Guid)(this["BillingAccountUpdateTestCharityId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0b96e1d3cc1016e223a85c15af8")]
        public string BillingAccountUpdateTestDefaultPaymentMethodId {
            get {
                return ((string)(this["BillingAccountUpdateTestDefaultPaymentMethodId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c6f9d451-d092-4df4-8b01-2ed552d7fcf2")]
        public global::System.Guid BillingAccountUpdateTestNonReferencedCreditMethodTypeId {
            get {
                return ((global::System.Guid)(this["BillingAccountUpdateTestNonReferencedCreditMethodTypeId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("642246")]
        public string BillingAccountsPOSTAccountIdTestUsa {
            get {
                return ((string)(this["BillingAccountsPOSTAccountIdTestUsa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("642229")]
        public string BillingAccountsPOSTAccountIdTestCanada {
            get {
                return ((string)(this["BillingAccountsPOSTAccountIdTestCanada"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("702fcf60-0cee-4d1e-b8f5-f50ac99539c9")]
        public global::System.Guid BillingPaymentMethodsEFFSPOSTPartyId {
            get {
                return ((global::System.Guid)(this["BillingPaymentMethodsEFFSPOSTPartyId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1f121ec7-4af2-4565-a0bf-6eae9696b2fc")]
        public global::System.Guid BillingApiPaymentMethodsEFTSPartyId {
            get {
                return ((global::System.Guid)(this["BillingApiPaymentMethodsEFTSPartyId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c93db826f41ff21016f684cf1c7326b")]
        public string BillingApiPaymentMethodsEFTSAccountId {
            get {
                return ((string)(this["BillingApiPaymentMethodsEFTSAccountId"]));
            }
        }
    }
}
