//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class EnrollTestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EnrollTestSettings defaultInstance = ((EnrollTestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EnrollTestSettings())));
        
        public static EnrollTestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640261")]
        public int AccountUpdateTestOwnerId {
            get {
                return ((int)(this["AccountUpdateTestOwnerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2c91a0b96e1d3cc1016e223b5af45afd")]
        public string AccountUpdateTestAccountId {
            get {
                return ((string)(this["AccountUpdateTestAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("91.84")]
        public decimal AccountRefundTestAmount {
            get {
                return ((decimal)(this["AccountRefundTestAmount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("641273")]
        public int AccountRefundTestOwnerId {
            get {
                return ((int)(this["AccountRefundTestOwnerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miao Laoshi")]
        public string AccountUpdateTestAccountNameOnAccount {
            get {
                return ((string)(this["AccountUpdateTestAccountNameOnAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4599")]
        public int AccountUpdateTestPaymentRequestId {
            get {
                return ((int)(this["AccountUpdateTestPaymentRequestId"]));
            }
        }
    }
}
