//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingTestCommon {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class BillingTestCommonSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BillingTestCommonSettings defaultInstance = ((BillingTestCommonSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BillingTestCommonSettings())));
        
        public static BillingTestCommonSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PVC413")]
        public string PromoCodeUsaCanada {
            get {
                return ((string)(this["PromoCodeUsaCanada"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUCAT1902")]
        public string PromoCodeAustralia {
            get {
                return ((string)(this["PromoCodeAustralia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TrxerConsole.exe")]
        public string TrxToHtmlTool {
            get {
                return ((string)(this["TrxToHtmlTool"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BillingTest")]
        public string TestResultTempFilePrefix {
            get {
                return ((string)(this["TestResultTempFilePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Visual Studio\\2017\\Enterprise")]
        public string VSIDEFolder {
            get {
                return ((string)(this["VSIDEFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BillingTestResults")]
        public string TestResultFolder {
            get {
                return ((string)(this["TestResultFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("billingtest")]
        public string TestResultMachine {
            get {
                return ((string)(this["TestResultMachine"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string TestEnv {
            get {
                return ((string)(this["TestEnv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0025700257")]
        public string BankAccountNumberCA {
            get {
                return ((string)(this["BankAccountNumberCA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125000024")]
        public string BankRoutineNumberUS {
            get {
                return ((string)(this["BankRoutineNumberUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("633000")]
        public string SaveUsaBankAccountBillingAccountId {
            get {
                return ((string)(this["SaveUsaBankAccountBillingAccountId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmailTestResults {
            get {
                return ((bool)(this["EmailTestResults"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test.emial.auto@trupanion.com")]
        public string EmailTestResultsFrom {
            get {
                return ((string)(this["EmailTestResultsFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yunfeng.ma@trupanion.com")]
        public string EmailTestResultsTo {
            get {
                return ((string)(this["EmailTestResultsTo"]));
            }
        }
    }
}
